services:
  web:
    container_name: tos-fe-web
    build: 
      context: ./TOS_FE
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    networks:
      - cont_network
    
networks:
  cont_network:
    external: true