services:
  web:
    container_name: frontend
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    networks:
      - cont_network
    
networks:
  cont_network:
    external: true