version: '3.8'

services:
  backend:
    build:
      context: ./TOS_BE
      dockerfile: Dockerfile
    container_name: tos-be-app
    ports:
      - "3000:3000"
    volumes:
      - ./TOS_BE/src:/usr/src/app/src
    environment:
      NODE_ENV: production
    networks:
      - cont_network

  frontend:
    build:
      context: ./TOS_FE
      dockerfile: Dockerfile
    container_name: tos-fe-web
    ports:
      - "8080:80"
    networks:
      - cont_network

  # database:
  #   image: postgres:latest
  #   container_name: tos-db
  #   environment:
  #     POSTGRES_USER: youruser
  #     POSTGRES_PASSWORD: yourpassword
  #     POSTGRES_DB: yourdb
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   networks:
  #     - cont_network

networks:
  cont_network:
    external: true
    # driver: bridge

# volumes:
#   db_data: