version: '3.8'

services:
  backend:
    build:
      context: ./TOS_BE
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./TOS_BE/src:/usr/src/app/src
    environment:
      NODE_ENV: production
      ALLOWED_ORIGINS: 'https://ticket.cypone.dev'
      API_URL: 'https://api.cypone.dev'
      DB_HOST: 'database'
      DB_USER: 'dbuser'
      DB_PASSWORD: 'dbpassword'
      DB_NAME: 'dbproj'
      JWT_SECRET: 'your_jwt_secret'
    restart: always
    networks:
      - cont_network

  frontend:
    build:
      context: ./TOS_FE
      dockerfile: Dockerfile
      args:
        VUE_APP_API_URL: https://api.cypone.dev
    container_name: frontend
    ports:
      - "8080:80"
    # environment:
    #    - VUE_APP_API_URL=http://localhost:3000
    restart: always
    networks:
      - cont_network

  database:
    build:
      context: ./TOS_DB
      dockerfile: Dockerfile
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbproj
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - cont_network

networks:
  cont_network:
    external: true
    # driver: bridge

volumes:
  db_data: