version: '3.8'

services:
  app:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build"
    environment:
      - NODE_ENV=production

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app