services:
  app:
    container_name: tos-be-app
    command: ["sh", "-c", "git clone https://github.com/bradly0cjw/Ticket_Order_System_BE.git ."]
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      NODE_ENV: production
    networks:
      - cont_network
    
networks:
  cont_network:
    external: true